### ISSUE TITLE
Bytecode breaks after instrumenting with soot in Program3

### ISSUE THREAD

**Issue by billy-mosse** [billy-mosse/jconsume#7]
When invoking daikon to analyze Program3's instrumented bytecode, it breaks.
Error:

`Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    ar/uba/dc/paper/Op.apply(Ljava/lang/Object;)Ljava/lang/Object; @41: invokestatic
  Reason:
    Type uninitialized 33 (current frame, stack[1]) is not assignable to 'java/util/Random'
  Current Frame:
    bci: @41
    flags: { }
    locals: { 'java/lang/Object', 'java/lang/Object', uninitialized 33, 'java/util/Date' }
    stack: { 'java/lang/Object', uninitialized 33, 'java/util/Date', 'java/lang/Object' }
  Bytecode:
    0x0000000: 014d 014e 014b 2b4b 2b2a b800 17bb 0019
    0x0000010: 4e2d b700 1a2b 2d2a b800 1e2b 2d2a b800
    0x0000020: 21bb 0023 4d2b 2c2d 2ab8 0027 2b2c 2db6
    0x0000030: 002b 3704 1604 b700 2e16 042c 2ab8 0032
    0x0000040: 2c2b c000 344e 2d2a 2bb8 0038 2db6 003c
    0x0000050: 592c 2a2b b800 402c b600 4368 3d1c 2a2b
    0x0000060: b800 47bb 0034 4e2d 1cb7 004a 1c2d 2a2b
    0x0000070: b800 4e2d b0                           

	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at daikon.chicory.DaikonVariableInfo.addClassVars(DaikonVariableInfo.java:448)
	at daikon.chicory.DaikonVariableInfo.addChildNodes(DaikonVariableInfo.java:1149)
	at daikon.chicory.DaikonVariableInfo.addParameters(DaikonVariableInfo.java:399)
	at daikon.chicory.RootInfo.enter_process(RootInfo.java:48)
	at daikon.chicory.Runtime.process_new_classes(Runtime.java:435)
	at daikon.chicory.Runtime.enter(Runtime.java:215)
	at ar.uba.dc.paper.InstrumentedMethod.ar_uba_dc_paper_Program2_CC_1300(InstrumentedMethod.java:8)
	at ar.uba.dc.paper.Program2.main(Program2.java)
	at ar.uba.dc.paper.Program2Test.main(Program2Test.java:10)

No program point declarations were found.
daikon.Daikon$TerminationMessage: No program point declarations were found.
	at daikon.Daikon.process_data(Daikon.java:2057)
	at daikon.Daikon.mainHelper(Daikon.java:563)
	at daikon.Daikon.main(Daikon.java:457)

`

**Comment by billy-mosse** [comment]
fdfc5f4
